var app = new Vue({
	el:"#app",
	data:{
        shop:[
            {
            	title:"车工官方旗舰店",
                goods:[
                    {
                    	title:"嘉实多",
                    	price:229.00,
                    	photo:"http://placehold.it/80X80",
                    	value:1,
                    	minprice:0
                    },
                    {
                    	title:"嘉实多",
                    	price:229.00,
                    	photo:"http://placehold.it/80X80",
                    	value:1,
                    	minprice:0
                    }
                ]
            },
            {
            	title:"东京自营",
            	goods:[
                    {
                    	title:"苹果",
                    	price:230.00,
                    	photo:"http://placehold.it/80X80",
                    	value:1,
                    	minprice:0
                    },
                    {
                    	title:"苹果",
                    	price:230.00,
                    	photo:"http://placehold.it/80X80",
                    	value:1,
                    	minprice:0
                    },
                    {
                    	title:"苹果",
                    	price:230.00,
                    	photo:"http://placehold.it/80X80",
                    	value:1,
                    	minprice:0
                    },
            	]
            }
        ]
	},
	methods:{
		add:function(index,aindex){
            this.shop[index].goods[aindex].value++;
		},
		reduce:function(index,aindex){
            this.shop[index].goods[aindex].value--;
            if(this.shop[index].goods[aindex].value<=0){
            	this.shop[index].goods[aindex].value=0;
            }
		}
	}
})